Repository yiisoft/injector, pull requests merged in 2020-04, with the labels that each got.

#4 Added `make` method and tests
  .phpstorm.meta.php
  README.md
  src/Injector.php
  tests/InjectorTest.php
  tests/Support/MakeEmptyConstructor.php
  tests/Support/MakeEngineCollector.php
  tests/Support/MakeEngineMatherWithParam.php
  tests/Support/MakeNoConstructor.php
  tests/Support/MakePrivateConstructor.php
Labels: status:code review

#6 Added support of arguments to be passed by reference
  src/Injector.php
  tests/InjectorTest.php
Labels: status:code review

#7 Simplify invoke()
  src/Injector.php
  tests/InjectorTest.php
  tests/Support/Invokeable.php
Labels: status:code review

#9 Refactoring and documentation
  README.md
  docs/en/README.md
  docs/en/img/algorithm.graphml
  docs/en/img/algorithm.svg
  docs/ru/README.md
  docs/ru/img/algorithm.graphml
  docs/ru/img/algorithm.svg
  src/Injector.php
  tests/InjectorTest.php
Labels: status:code review, type:docs

#10 Fix parameter solving for an internal functions
  src/ArgumentException.php
  src/Injector.php
  src/InvalidArgumentException.php
  src/MissingInternalArgumentException.php
  src/MissingRequiredArgumentException.php
  tests/InjectorTest.php
Labels: status:code review

#12 Added ArgumentException tests
  src/MissingInternalArgumentException.php
  tests/ArgumentExceptionTest.php
  tests/InvalidArgumentExceptionTest.php
  tests/MissingInternalArgumentExceptionTest.php
  tests/MissingRequiredArgumentExceptionTest.php
Labels: status:code review, type:test
