Repository yiisoft/injector, pull requests merged in 2022-05, with the labels that each got.

#63 Better Closure rendering (compatible with php 8.1)
  CHANGELOG.md
  src/ArgumentException.php
  tests/Common/ArgumentExceptionTest.php
  tests/Php8/ArgumentExceptionTest.php
  tests/Php8/Support/TypesIntersection.php
Labels: type:enhancement

#62 Use reusables actions.
  .github/workflows/build.yml
  .github/workflows/mutation.yml
  .github/workflows/static.yml
  .scrutinizer.yml
Labels: status:code review

#64 Support for type intersection resolving
  .github/workflows/static.yml
  CHANGELOG.md
  src/ArgumentException.php
  src/Injector.php
  src/ResolvingState.php
  tests/Php8/InjectorTest.php
  tests/Php8/Support/TypesIntersection.php
  tests/Php8/Support/TypesIntersectionReferencedConstructor.php
Labels: status:code review, type:feature
